
package com.meriame.soapservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Admin", targetNamespace = "http://soapService.meriame.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Admin {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAgence", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.DeleteAgence")
    @ResponseWrapper(localName = "deleteAgenceResponse", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.DeleteAgenceResponse")
    public boolean deleteAgence(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.meriame.soapservice.AgenceSOAPDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editAgence", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.EditAgence")
    @ResponseWrapper(localName = "editAgenceResponse", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.EditAgenceResponse")
    public AgenceSOAPDTO editAgence(
        @WebParam(name = "arg0", targetNamespace = "")
        AgenceSOAPDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.meriame.soapservice.AgentSOAPDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editAgent", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.EditAgent")
    @ResponseWrapper(localName = "editAgentResponse", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.EditAgentResponse")
    public AgentSOAPDTO editAgent(
        @WebParam(name = "arg0", targetNamespace = "")
        AgentSOAPDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAgent", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.DeleteAgent")
    @ResponseWrapper(localName = "deleteAgentResponse", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.DeleteAgentResponse")
    public boolean deleteAgent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.meriame.soapservice.AgenceSOAPDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAgence", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.GetAgence")
    @ResponseWrapper(localName = "getAgenceResponse", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.GetAgenceResponse")
    public List<AgenceSOAPDTO> getAgence(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.meriame.soapservice.AgentSOAPDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAgent", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.AddAgent")
    @ResponseWrapper(localName = "addAgentResponse", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.AddAgentResponse")
    public AgentSOAPDTO addAgent(
        @WebParam(name = "arg0", targetNamespace = "")
        AgentSOAPDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AdminLogin")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AdminLogin", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.AdminLogin")
    @ResponseWrapper(localName = "AdminLoginResponse", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.AdminLoginResponse")
    public boolean adminLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.meriame.soapservice.AgentSOAPDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAgent", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.GetAgent")
    @ResponseWrapper(localName = "getAgentResponse", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.GetAgentResponse")
    public List<AgentSOAPDTO> getAgent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.meriame.soapservice.AgenceSOAPDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAgence", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.AddAgence")
    @ResponseWrapper(localName = "addAgenceResponse", targetNamespace = "http://soapService.meriame.com/", className = "com.meriame.soapservice.AddAgenceResponse")
    public AgenceSOAPDTO addAgence(
        @WebParam(name = "arg0", targetNamespace = "")
        AgenceSOAPDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
